main/users/blueprint.py
from flask import Blueprint, render_template, request, redirect
from main.model import user
from main import db
from main import cache
import time

# instanciate objects
users = Blueprint('users', __name__, template_folder='templates')
User = user.User;

"""
    These endpoints are used in the User Router to fetch users.
    They are cached and the response is stored based on Query String. 
    The timeout is default, set in the config app - 300 seconds
    timeout param is the time that this response will be cached in Redis memory.
    
    NOTE: RedisCache is already available in werkzeug >= 0.7 no need for a special configuration
"""

# Main router not cached, used when back from Edit or Delete
# localhost:5000/users/
@users.route('/')
def users_list():
    start_time = time.time()
    args       = request.args
    per_page   = 15
    page_num   = args.get('page_num') if args.get('page_num') != None else 1
    try:
        users = User.query.order_by(User.lastName).paginate(page=int(page_num), per_page=int(per_page), error_out=True)
    except Exception as err:
        print("ERROR** Module User Router - users_list()", str(err))
        users = []; filterName='';

    print("--- %s seconds ---" % (time.time() - start_time))       
    return render_template('users/users.html', data_set=users)


# Main router  cached, used in Button All Results
# localhost:5000/users/memoize
@users.route('/memoize')
@cache.memoize()
def users_list_memo():
    start_time = time.time()
    args       = request.args
    per_page   = 15
    page_num   = args.get('page_num') if args.get('page_num') != None else 1
    try:
        users = User.query.order_by(User.lastName).paginate(page=int(page_num), per_page=int(per_page), error_out=True)
    except Exception as err:
        print("ERROR** Module User Router - users_list()", str(err))
        users = []; filterName='';

    print("--- %s memoize ---" % (time.time() - start_time))       
    return render_template('users/users.html', data_set=users)

"""
param query_string: 
    When True, the cache key used will be the result of hashing the ordered query string parameters. 
    This avoids creating different caches for the same query just because the parameters were passed in a different order.
"""
# localhost:5000/users/search
@users.route('/search')
@cache.cached(query_string=True)
def users_search():
    start_time = time.time()
    args       = request.args
    per_page   = 15
    filterName = args.get("name")
    page_num   = args.get('page_num') if args.get('page_num') != None else 1
    try:
        if filterName != None and filterName != '':
            filterCondition = (User.firstName.ilike("%"+str(filterName)+"%") | User.lastName.ilike("%"+str(filterName)+"%"))
            users = User.query.filter(filterCondition).order_by(User.lastName).paginate(page=int(page_num), per_page=int(per_page), error_out=True)
        else:
            users = User.query.order_by(User.lastName).paginate(page=int(page_num), per_page=int(per_page), error_out=True)
    except Exception as err:
        print("ERROR** Module User Router - users_search()", str(err))
        users = []; filterName='';

    print("--- %s seconds ---" % (time.time() - start_time)) 
    return render_template('users/users.html', filterName=filterName, data_set=users)

''' 
    By default, Flask accepts GET requests for all routes, I added here it to allow GET and POST requests
    if request.form checks if someone just submitted the form. 
    If they did, we can access the data that they submitted through the request.form variable
    Flask represents all of the form data as an ImmutableMultiDict, which is just a fancy Python dictionary.
    It stored our user's input as a tuple
'''
# localhost:5000/users/create
@users.route('/create',methods=["GET", "POST"])
def user_create():
    if request.form:
        newUser = User(firstName=request.form.get("firstName"), lastName=request.form.get("lastName"), bio=request.form.get("bio"))
        db.session.add(newUser)
        db.session.commit()
    return render_template('users/user_create.html')

'''
    This method will just redirect to a delete or update template
'''
# localhost:5000/users/redirect
@users.route("/redirect")
def user_redirect():
    try:
        args = request.args
        if args.get('selected'):
            userFound = User.query.filter_by(id=args.get('selected')).first()
        if args.get('action') == 'edit' and userFound:
            return render_template('users/user_update.html', selected=userFound)
        elif args.get('action') == 'delete' and userFound:
            return render_template('users/user_delete.html', selected=userFound)
        else:
            return redirect("/users/")
    except Exception as err:
        print("ERROR** Module User Router - redirect()", str(err))
        return redirect("/users/")

'''
    Find user by the id selected and sent by param and edit the first name
'''
# localhost:5000/users/update
@users.route("/update", methods=["POST"])
def user_update():
    try:
        firstName = request.form.get("firstName")
        userId    = request.form.get("userId")
        userFound = User.query.filter_by(id=userId).first()
        userFound.firstName = firstName
        db.session.commit()
    except Exception as err:
        print("ERROR** Module User Router - redirect()", str(err))
    return redirect("/users/")


'''
    Find user by the id selected and sent by param and delete it by id
'''
# localhost:5000/users/delete
@users.route("/delete", methods=["POST"])
def user_delete():
    try:
        userId = request.form.get("userId")
        userFound = User.query.filter_by(id=userId).first()
        db.session.delete(userFound)
        db.session.commit()
    except Exception as err:
        print("ERROR** Module User Router - redirect()", str(err))
    return redirect("/users/")

main/users/templates/users/user_create.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" 
                integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Create User</title>
  </head>
  <body>
    <div class="container" style="margin-top:1.5em;">
      <h3>
          Create User
      </h3>
      <form method="POST" action="/users/create" class="d-flex flex-column">
        <label for="firstname">First Name</label>
        <input class="form-control p-2" type="text" name="firstName" id="firstname">
        <label for="lastname">Last Name</label>
        <input class="form-control p-2" type="text" name="lastName" id="lastname">
        <label for="bio">First Name</label>
        <input class="form-control p-2" type="text" name="bio" id="bio">
        <button class="btn btn-secondary col-1 text-center" type="submit" style="margin-top:1.5em;">Add</button>
      </form>
      <form action="/users" class="col-1" style="margin-top:1.5em; width: 100%;">
        <button class="btn btn-secondary">Back</button>
      </form>
  </div>
  </body>
</html>

main/users/templates/users/user_delete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" 
                integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Users-Delete</title>
  </head>
  <body>
    <div class="container" style="margin-top:1.5em;">
      <h3>
          Delete User
      </h3>
      <form method="POST" action="/users/delete" class="d-flex p-2 bd-highlight">
        <input type="hidden" value="{{selected.id}}" name="userId">
        <input class="form-control" type="text" value="{{selected.firstName}}" name="firstName" style="margin-right:1.5em;">
        <input class="btn btn-secondary" type="submit" value="Delete">
      </form>
      <form action="/users" class="d-flex p-2 bd-highlight">
        <button class="btn btn-secondary">Back</button>
      </form>
  </div>
  </body>
</html>

main/users/templates/users/user_update.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" 
                integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Users-Update</title>
  </head>
  <body>
    <div class="container" style="margin-top:1.5em;">
      <h3>
          Update User
      </h3>
      <form method="POST" action="/users/update" class="d-flex p-2 bd-highlight">
        <input type="hidden" value="{{selected.id}}" name="userId">
        <input class="form-control" type="text" value="{{selected.firstName}}" name="firstName" style="margin-right:1.5em;">
        <input class="btn btn-secondary" type="submit" value="Update">
      </form>
      <form action="/users" class="d-flex p-2 bd-highlight">
        <button class="btn btn-secondary">Back</button>
      </form>
  </div>
  </body>
</html>

main/users/templates/users/users.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" 
                    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <title>Search Users</title>
    </head>
    <body>
        <!-- (DOC) Forms are by default a method GET, but let´s add anyways to be readable -->
        <div class="container" style="margin-top:1.5em;">
            <h3>
                Users table
                <small class="text-muted">Find users by first name or last name</small>
            </h3>
            <form class="form-inline my-2 my-lg-0 p-1" method="GET" action="/users/memoize">
                <button class="btn btn-outline-success p-1" type="submit" id="btn-clearsearch">All Results</button>
            </form>
            <form class="form-inline my-2 my-lg-0 p-1" action="/users/create">
                <button class="btn btn-outline-success p-1" id="btn-create">New User</button>
            </form>
            <form class="form-inline my-2 my-lg-0" method="GET" action="/users/search">
                <!-- (DOC)  When a user submit the form a data sent to the server will be a -name value pair- name is the var to userData and value is what user types. Value auto added to the submit-->
                <div class="d-flex p-1 flex-row justify-content-start">
                    <input class="form-control col-md-4" type="search" placeholder="Search Users" name="name" style="width:50%">
                    <!-- (DOC) submit function in users blueprint will handle the args name  -->
                    <button class="btn btn-outline-success p-1" type="submit"id="btn-searchusers" style="width:10%; margin-left:12px;">Search</button>
                </div>
                <table class="table" data-pagination="true">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">First Name</th>
                        <th scope="col">Last Name</th>
                        <th scope="col">Bio</th>
                        <th scope="col">User Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                        <!-- (DOC) if the result set has total value greater than zero, show the pagination -->
                        <div class="d-flex p-1 flex-col justify-content-start">
                            {% if data_set.total and data_set.total > 0 %}
                                <p class="p-1">Total results {{ data_set.total}}</p> 
                            {% endif %}
                            {% if filterName|length > 0 %}
                                <p class="p-1">Searching for {{filterName}}</p> 
                            {% endif %}
                        </div>
                        {% if data_set.total and data_set.total > 0 %}
                            {% for user in data_set %}
                                <tr>
                                    <th scope="row">{{ loop.index }}</th>
                                    <td>{{user.firstName}}</td>
                                    <td>{{user.lastName}}</td>
                                    <td>{{user.bio}}</td>
                                    <td>
                                        <a href="{{ url_for('users.user_redirect', action='edit', selected=user.id) }}">Edit</a>
                                        <a href="{{ url_for('users.user_redirect', action='delete', selected=user.id) }}">Delete</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                        <!-- (DOC) if nothing is found, shouw to users a row message  -->
                            <tr>
                                <th scope="row">#</th>
                                <td colspan="3">No users found</td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
                {% if data_set.total %}
                    
                    <p>Page Selected {{data_set.next_num}}</p>
                    
                    <!-- previous page -->
                    {% if data_set.has_prev %}
                        <a href="{{ url_for('users.users_search',page_num=data_set.prev_num,  name=filterName) }}">Previous</a>
                    {% endif %}
                    <!-- all page numbers -->
                    {% for pg in data_set.iter_pages() %}
                        {% if pg %}
                            {% if pg != data_set.page_num %}
                                <a href="{{ url_for('users.users_search', page_num=pg, name=filterName) }}">{{ pg }}</a>
                            {% else %}
                                <a href="#">{{ pg }}</a>
                            {% endif %}
                            {% else %}
                                <span class="ellipsis" style="white-space; nowrap; overflow: hidden; text-overflow: ellipsis">…</span>
                        {% endif %}
                    {% endfor %}
                    <!-- next page -->
                    {% if data_set.has_next %}
                        <a href="{{ url_for('users.users_search',page_num=data_set.next_num,  name=filterName) }}">Next</a>
                    {% endif %}
                {% endif %}
            </form>
            <form action="/">
                <button type="submit" class="btn btn-secondary mb-4">Back to Home</button>
            </form>
        </div>
    </body>
</html>